In [6]:
import torch.nn as nn
import torch

In [2]:
emb1 = nn.Embedding(2,2)
emb2 = nn.Embedding(2,2)

In [3]:
emb1.weight

Parameter containing:
tensor([[ 0.0745, -0.2656],
        [ 2.0636,  0.1522]], requires_grad=True)

In [4]:
emb2.weight

Parameter containing:
tensor([[-0.7435, -0.5083],
        [ 0.9306,  0.0637]], requires_grad=True)

In [5]:
token_shift = 58888

In [7]:
input_ids = torch.tensor([1,0,token_shift+0,token_shift+0])

In [8]:
emb1_mask = torch.tensor([input_id - token_shift < 0 for input_id in input_ids])

In [9]:
emb1_mask

tensor([ True,  True, False, False])

In [13]:
ind_emb1 = torch.where(emb1_mask, input_ids, torch.zeros_like(input_ids))
ind_emb2 = torch.where(~emb1_mask, input_ids - token_shift, torch.zeros_like(input_ids))

In [14]:
ind_emb1

tensor([1, 0, 0, 0])

In [15]:
ind_emb2

tensor([0, 0, 0, 0])

In [16]:
emb_arr1 = emb1(ind_emb1)
emb_arr2 = emb2(ind_emb2)

In [17]:
emb_arr1

tensor([[ 2.0636,  0.1522],
        [ 0.0745, -0.2656],
        [ 0.0745, -0.2656],
        [ 0.0745, -0.2656]], grad_fn=<EmbeddingBackward0>)

In [20]:
emb_arr2

tensor([[-0.7435, -0.5083],
        [-0.7435, -0.5083],
        [-0.7435, -0.5083],
        [-0.7435, -0.5083]], grad_fn=<EmbeddingBackward0>)

In [21]:
res = torch.where(emb1_mask.unsqueeze(-1), emb_arr1, emb_arr2)
res

tensor([[ 2.0636,  0.1522],
        [ 0.0745, -0.2656],
        [-0.7435, -0.5083],
        [-0.7435, -0.5083]], grad_fn=<WhereBackward0>)